wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713854973.0
    t:
      1:
      - 1
      - 37
      - 38
      - 41
      - 55
      2:
      - 1
      - 37
      - 38
      - 41
      - 55
      3:
      - 3
      - 23
      - 61
      4: 3.8.19
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
angle_version:
  desc: null
  value: le90
auto_resume:
  desc: null
  value: false
checkpoint_config:
  desc: null
  value:
    interval: 4
data:
  desc: null
  value:
    samples_per_gpu: 2
    workers_per_gpu: 2
    train:
      type: DOTADataset
      ann_file: data/split_ss_dota/trainval/annfiles/
      img_prefix: data/split_ss_dota/trainval/images/
      pipeline:
      - type: LoadImageFromFile
      - type: LoadAnnotations
        with_bbox: true
      - type: RResize
        img_scale:
        - 1024
        - 1024
      - type: RRandomFlip
        flip_ratio:
        - 0.25
        - 0.25
        - 0.25
        direction:
        - horizontal
        - vertical
        - diagonal
        version: le90
      - type: Normalize
        mean:
        - 123.675
        - 116.28
        - 103.53
        std:
        - 58.395
        - 57.12
        - 57.375
        to_rgb: true
      - type: Pad
        size_divisor: 32
      - type: DefaultFormatBundle
      - type: Collect
        keys:
        - img
        - gt_bboxes
        - gt_labels
      version: le90
    val:
      type: DOTADataset
      ann_file: data/split_ss_dota/trainval/annfiles/
      img_prefix: data/split_ss_dota/trainval/images/
      pipeline:
      - type: LoadImageFromFile
      - type: MultiScaleFlipAug
        img_scale:
        - 1024
        - 1024
        flip: false
        transforms:
        - type: RResize
        - type: Normalize
          mean:
          - 123.675
          - 116.28
          - 103.53
          std:
          - 58.395
          - 57.12
          - 57.375
          to_rgb: true
        - type: Pad
          size_divisor: 32
        - type: DefaultFormatBundle
        - type: Collect
          keys:
          - img
      version: le90
    test:
      type: DOTADataset
      ann_file: data/split_ss_dota/test/images/
      img_prefix: data/split_ss_dota/test/images/
      pipeline:
      - type: LoadImageFromFile
      - type: MultiScaleFlipAug
        img_scale:
        - 1024
        - 1024
        flip: false
        transforms:
        - type: RResize
        - type: Normalize
          mean:
          - 123.675
          - 116.28
          - 103.53
          std:
          - 58.395
          - 57.12
          - 57.375
          to_rgb: true
        - type: Pad
          size_divisor: 32
        - type: DefaultFormatBundle
        - type: Collect
          keys:
          - img
      version: le90
data_root:
  desc: null
  value: data/split_ss_dota/
dataset_type:
  desc: null
  value: DOTADataset
dist_params:
  desc: null
  value:
    backend: nccl
evaluation:
  desc: null
  value:
    interval: 4
    metric: mAP
gpu_ids:
  desc: null
  value:
  - 0
img_norm_cfg:
  desc: null
  value:
    mean:
    - 123.675
    - 116.28
    - 103.53
    std:
    - 58.395
    - 57.12
    - 57.375
    to_rgb: true
load_from:
  desc: null
  value: null
log_config:
  desc: null
  value:
    interval: 50
    hooks:
    - type: TextLoggerHook
    - type: MMDetWandbHook
      init_kwargs:
        project: MMDetection-tutorial
      interval: 10
      log_checkpoint: true
      num_eval_images: 0
log_level:
  desc: null
  value: INFO
lr_config:
  desc: null
  value:
    policy: step
    warmup: linear
    warmup_iters: 500
    warmup_ratio: 0.3333333333333333
    step:
    - 8
    - 11
model:
  desc: null
  value:
    type: OrientedRCNN
    backbone:
      type: ResNet
      depth: 50
      num_stages: 4
      out_indices:
      - 0
      - 1
      - 2
      - 3
      frozen_stages: 1
      norm_cfg:
        type: BN
        requires_grad: true
      norm_eval: true
      style: pytorch
      init_cfg:
        type: Pretrained
        checkpoint: torchvision://resnet50
    neck:
      type: FPN
      in_channels:
      - 256
      - 512
      - 1024
      - 2048
      out_channels: 256
      num_outs: 5
    rpn_head:
      type: OrientedRPNHead
      in_channels: 256
      feat_channels: 256
      version: le90
      anchor_generator:
        type: AnchorGenerator
        scales:
        - 8
        ratios:
        - 0.5
        - 1.0
        - 2.0
        strides:
        - 4
        - 8
        - 16
        - 32
        - 64
      bbox_coder:
        type: MidpointOffsetCoder
        angle_range: le90
        target_means:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        target_stds:
        - 1.0
        - 1.0
        - 1.0
        - 1.0
        - 0.5
        - 0.5
      loss_cls:
        type: CrossEntropyLoss
        use_sigmoid: true
        loss_weight: 1.0
      loss_bbox:
        type: SmoothL1Loss
        beta: 0.1111111111111111
        loss_weight: 1.0
    roi_head:
      type: OrientedStandardRoIHead
      bbox_roi_extractor:
        type: RotatedSingleRoIExtractor
        roi_layer:
          type: RoIAlignRotated
          out_size: 7
          sample_num: 2
          clockwise: true
        out_channels: 256
        featmap_strides:
        - 4
        - 8
        - 16
        - 32
      bbox_head:
        type: RotatedShared2FCBBoxHead
        in_channels: 256
        fc_out_channels: 1024
        roi_feat_size: 7
        num_classes: 15
        bbox_coder:
          type: DeltaXYWHAOBBoxCoder
          angle_range: le90
          norm_factor: null
          edge_swap: true
          proj_xy: true
          target_means:
          - 0.0
          - 0.0
          - 0.0
          - 0.0
          - 0.0
          target_stds:
          - 0.1
          - 0.1
          - 0.2
          - 0.2
          - 0.1
        reg_class_agnostic: true
        loss_cls:
          type: CrossEntropyLoss
          use_sigmoid: false
          loss_weight: 1.0
        loss_bbox:
          type: SmoothL1Loss
          beta: 1.0
          loss_weight: 1.0
    train_cfg:
      rpn:
        assigner:
          type: MaxIoUAssigner
          pos_iou_thr: 0.7
          neg_iou_thr: 0.3
          min_pos_iou: 0.3
          match_low_quality: true
          ignore_iof_thr: -1
        sampler:
          type: RandomSampler
          num: 256
          pos_fraction: 0.5
          neg_pos_ub: -1
          add_gt_as_proposals: false
        allowed_border: 0
        pos_weight: -1
        debug: false
      rpn_proposal:
        nms_pre: 2000
        max_per_img: 2000
        nms:
          type: nms
          iou_threshold: 0.8
        min_bbox_size: 0
      rcnn:
        assigner:
          type: MaxIoUAssigner
          pos_iou_thr: 0.5
          neg_iou_thr: 0.5
          min_pos_iou: 0.5
          match_low_quality: false
          iou_calculator:
            type: RBboxOverlaps2D
          ignore_iof_thr: -1
        sampler:
          type: RRandomSampler
          num: 512
          pos_fraction: 0.25
          neg_pos_ub: -1
          add_gt_as_proposals: true
        pos_weight: -1
        debug: false
    test_cfg:
      rpn:
        nms_pre: 2000
        max_per_img: 2000
        nms:
          type: nms
          iou_threshold: 0.8
        min_bbox_size: 0
      rcnn:
        nms_pre: 2000
        min_bbox_size: 0
        score_thr: 0.05
        nms:
          iou_thr: 0.1
        max_per_img: 2000
mp_start_method:
  desc: null
  value: fork
opencv_num_threads:
  desc: null
  value: 0
optimizer:
  desc: null
  value:
    type: SGD
    lr: 0.005
    momentum: 0.9
    weight_decay: 0.0001
optimizer_config:
  desc: null
  value:
    grad_clip:
      max_norm: 35
      norm_type: 2
resume_from:
  desc: null
  value: null
runner:
  desc: null
  value:
    type: EpochBasedRunner
    max_epochs: 12
test_pipeline:
  desc: null
  value:
  - type: LoadImageFromFile
  - type: MultiScaleFlipAug
    img_scale:
    - 1024
    - 1024
    flip: false
    transforms:
    - type: RResize
    - type: Normalize
      mean:
      - 123.675
      - 116.28
      - 103.53
      std:
      - 58.395
      - 57.12
      - 57.375
      to_rgb: true
    - type: Pad
      size_divisor: 32
    - type: DefaultFormatBundle
    - type: Collect
      keys:
      - img
train_pipeline:
  desc: null
  value:
  - type: LoadImageFromFile
  - type: LoadAnnotations
    with_bbox: true
  - type: RResize
    img_scale:
    - 1024
    - 1024
  - type: RRandomFlip
    flip_ratio:
    - 0.25
    - 0.25
    - 0.25
    direction:
    - horizontal
    - vertical
    - diagonal
    version: le90
  - type: Normalize
    mean:
    - 123.675
    - 116.28
    - 103.53
    std:
    - 58.395
    - 57.12
    - 57.375
    to_rgb: true
  - type: Pad
    size_divisor: 32
  - type: DefaultFormatBundle
  - type: Collect
    keys:
    - img
    - gt_bboxes
    - gt_labels
work_dir:
  desc: null
  value: ./work_dirs/oriented_rcnn_r50_fpn_1x_dota_le90_customized
workflow:
  desc: null
  value:
  - - train
    - 1
